// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ConnectionStatus: typeof import('./components/ConnectionStatus.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScannerComponent: typeof import('./components/ScannerComponent.vue')['default']
    SelectLocatie: typeof import('./components/SelectLocatie.vue')['default']
    StatusBar: typeof import('./components/StatusBar.vue')['default']
  }
}
